sudo: required
dist: trusty
language: php
php:
# Broken on Travis
#  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
addons:
  firefox: 'latest'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
env:
  global:
  - FIREFOX_NIGHTLY_BIN=firefox
  - CHROME_BIN=google-chrome-stable
  matrix:
  - WP_VERSION=3.8 WP_MULTISITE=0
  - WP_VERSION=3.9 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
matrix:
  allow_failures:
    - php: 7.0
install:
  - ./bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install --working-dir=wp-offline-content --optimize-autoloader
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - make ci-lint
  - make test
  - make test-sw

